"""add invert_amounts column to bank accounts

Revision ID: 05bb0c54178d
Revises: 
Create Date: 2026-06-23 10:00:42.152611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bb0c54178d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('invert_amounts', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_expenses_account_id', 'bank_accounts', ['account_id'], ['account_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('invert_amounts')

    # ### end Alembic commands ###
